### ISSUE TITLE
Users' Password Can't be Changed

### ISSUE THREAD

**Issue by selmanceker** [radity/rcrm#4]
rcrm_account > 
- PasswordChangeForm, 
- ChangePasswordView, 
- UserProfileView, 
- path('profile/', ...

Form UserProfileView ile template getiriliyor, ChangePasswordView ile post ediliyor. 

Hata mesaji: http://dpaste.com/2EG898A

**Comment by oaksakal** [comment]
English please:)

selmanceker <notifications@github.com> schrieb am Mo., 9. Juli 2018, 22:07:

**Comment by selmanceker** [comment]
rcrm_account >

PasswordChangeForm,
ChangePasswordView,
UserProfileView,
path('profile/', ...
Form is gotten using UserProfileView, with ChangePasswordView it posts.

Error message: http://dpaste.com/2EG898A

**Comment by oaksakal** [comment]
Şakaydı. Geleceğe yönelik:)

Am 09.07.2018 22:44 schrieb "selmanceker" <notifications@github.com>:

rcrm_account >

PasswordChangeForm,
ChangePasswordView,
UserProfileView,
path('profile/', ...
Form is gotten using UserProfileView, with ChangePasswordView it posts.

Error message: http://dpaste.com/2EG898A

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/radity/rcrm/issues/4#issuecomment-403614113>, or mute
the thread

**Comment by selmanceker** [comment]
Simdiden aliskanlik edinmek iyi olur tabii :)

Şakaydı. Geleceğe yönelik:)

Am 09.07.2018 22:44 schrieb "selmanceker" <notifications@github.com>:

rcrm_account >

PasswordChangeForm,
ChangePasswordView,
UserProfileView,
path('profile/', ...
Form is gotten using UserProfileView, with ChangePasswordView it posts.

Error message: http://dpaste.com/2EG898A

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<#4 (comment)>, or mute
the thread
